### ISSUE TITLE
[BUG] virials issue in vasprun.xml

### ISSUE THREAD

**Issue by HsuQuinn** [deepmodeling/dpdata#536] opened 2023-09-07 03:36 UTC
**Summary**
With similar issue of #212:  

data["virials"][ii] *= v_pref * vol
IndexError: index 0 is out of bounds for axis 0 with size 0

Here is INCAR and vasp.xml. 
[file.zip](https://github.com/deepmodeling/dpdata/files/12544349/file.zip)

**Comment by wanghan-iapcm** [comment] 2023-09-08 02:04
By your INCAR the stress is not calculated. plz assign ISIF >= 2

**Comment by HsuQuinn** [comment] 2023-09-08 02:12
ok, thanks

**Comment by njzjz** [comment] 2023-11-05 17:56
Since this issue is duplicate of #212, I am going to close the issue and track the problem in that issue.

**Closed** 2023-11-05 17:56 UTC
Labels: bug, duplicate, vasp
