### ISSUE TITLE
[BUG] dpdata extracts incorrect box information when extracting NPT_F dynamics trajectories calculated by cp2k (version 7.1)

### ISSUE THREAD

**Issue by xiaohe-njust** [deepmodeling/dpdata#589] opened 2023-12-21 02:31 UTC
### Bug summary

dpdata extracts incorrect box information when extracting NPT_F dynamics trajectories calculated by cp2k (version 7.1)

### dpdata Version

v0.2.17

### Input Files, Running Commands, Error Log, etc.

`import dpdata `
`import numpy as np  `
`data = dpdata.LabeledSystem('npt-30GPa', fmt = 'cp2k/aimd_output')` 
`data[20000].to_deepmd_raw("dpdata-30GPa-f20000")`

[30GPa-last frame.zip](https://github.com/deepmodeling/dpdata/files/13749061/30GPa-last.frame.zip)

![bug](https://github.com/deepmodeling/dpdata/assets/133549998/28ebc4b3-b4fd-42ff-abb0-4e7d9da3259f)

### Steps to Reproduce

dpdata extracts incorrect box information when extracting NPT_F dynamics trajectories calculated by cp2k (version 7.1)
I took the information from the last frame extracted by dpdata and compared it to the information in the restart file, the coordinate information is consistent, the box information is not. I viewed the two box information in ovito by adding each to the coordinate information of the last frame, and the box size information in the restart file is correct, the box information extracted by dpdata is incorrect, resulting in an error in the molecular structure when processing the periodicity.

**Comment by robinzyb** [comment] 2023-12-25 09:39
please provdie the cp2k output files for me to debug. 
```
Archive:  30GPa-last.frame.zip
   creating: dpdata-30GPa-f20000/
  inflating: dpdata-30GPa-f20000/box.raw  
  inflating: dpdata-30GPa-f20000/coord.raw  
  inflating: dpdata-30GPa-f20000/energy.raw  
  inflating: dpdata-30GPa-f20000/force.raw  
  inflating: dpdata-30GPa-f20000/type.raw  
  inflating: dpdata-30GPa-f20000/type_map.raw  
  inflating: cp2k-1.restart          

```
also, have you tried cp2kdata plugin? 
https://github.com/robinzyb/cp2kdata/tree/main

**Comment by xiaohe-njust** [comment] 2023-12-25 13:05
@robinzyb I computed a ten frame NPT dynamics trajectory and output the real box information file (cp2k-1.cell) for your reference.

I found that dpdata is converting the Cell lengths and Cell angles information from the cp2k output file into box information, but this conversion does not determine the position of the box, which is rotated compared to the actual box. However, the information such as atomic coordinates are relative to the actual box, which causes the error periodic  handling.

I have tried using the cp2kdata plugin and it extracts fine for cp2k version 2023 but reports errors for version 7.1. cp2kdata extracts the box information from Cell lengths and Cell angles information as well, hence the same error.

[NPT_F-trajectory.zip](https://github.com/deepmodeling/dpdata/files/13766112/NPT_F-trajectory.zip)

**Comment by xiaohe-njust** [comment] 2023-12-25 13:12
> please provide the cp2k output files for me to debug.
> 
> ```
> Archive:  30GPa-last.frame.zip
>    creating: dpdata-30GPa-f20000/
>   inflating: dpdata-30GPa-f20000/box.raw  
>   inflating: dpdata-30GPa-f20000/coord.raw  
>   inflating: dpdata-30GPa-f20000/energy.raw  
>   inflating: dpdata-30GPa-f20000/force.raw  
>   inflating: dpdata-30GPa-f20000/type.raw  
>   inflating: dpdata-30GPa-f20000/type_map.raw  
>   inflating: cp2k-1.restart          
> ```
> 
> also, have you tried cp2kdata plugin? https://github.com/robinzyb/cp2kdata/tree/main

@robinzyb  I computed a ten frame NPT dynamics trajectory and output the real box information file (cp2k-1.cell) for your reference.

I found that dpdata is converting the Cell lengths and Cell angles information from the cp2k output file into box information, but this conversion does not determine the position of the box, which is rotated compared to the actual box. However, the information such as atomic coordinates are relative to the actual box, which causes the error periodic handling.

I have tried using the cp2kdata plugin and it extracts fine for cp2k version 2023 but reports errors for version 7.1. cp2kdata extracts the box information from Cell lengths and Cell angles information as well, hence the same error.


[NPT_F-trajectory.zip](https://github.com/deepmodeling/dpdata/files/13766132/NPT_F-trajectory.zip)

**Comment by robinzyb** [comment] 2023-12-26 10:48
I can't reproduce the mismatch using cp2kdata. Here are my results
Directories:
```
.
├── NPT_F-trajectory
│   ├── cp2k-1.cell
│   ├── cp2k-1.ener
│   ├── cp2k-1.restart
│   ├── cp2k-frc-1.xyz
│   ├── cp2k-pos-1.xyz
│   ├── cp2k.err
│   ├── cp2k.inp
│   ├── cp2k.log
│   └── dpdata
│       ├── box.raw
│       ├── coord.raw
│       ├── energy.raw
│       ├── force.raw
│       ├── type.raw
│       └── type_map.raw
├── NPT_F-trajectory.zip
├── deepmd
│   ├── box.raw
│   ├── coord.raw
│   ├── energy.raw
│   ├── force.raw
│   ├── set.000
│   │   ├── box.npy
│   │   ├── coord.npy
│   │   ├── energy.npy
│   │   └── force.npy
│   ├── type.raw
│   └── type_map.raw
└── test.ipynb

5 directories, 26 files
```
```python
import dpdata
cp2kmd_dir = "./NPT_F-trajectory/"
cp2kmd_output_name = "cp2k.log"
dp = dpdata.LabeledSystem(cp2kmd_dir, cp2k_output_name=cp2kmd_output_name, fmt="cp2kdata/md")
print(dp)
```
```stdout
--- You are parsing data using package Cp2kData ---
Parsing Energies from ./NPT_F-trajectory/cp2k-1.ener
Parsing Structures from ./NPT_F-trajectory/cp2k-pos-1.xyz
Parsing Froces from ./NPT_F-trajectory/cp2k-frc-1.xyz
Parsing Stress from the CP2K output/log file: ./NPT_F-trajectory/cp2k.log
Parsing Cells from ./NPT_F-trajectory/cp2k-1.cell
Atom names are fake chemical symbols as you set in cp2k input.
--- You are parsing data using package Cp2kData ---
Data Summary
Labeled System
-------------------
Frame Numbers      : 11
Atom Numbers       : 192
Including Virials  : No
Element List       :
-------------------
O  N  C  H
32  80  16  64

```
```python
import numpy as np
# load numpy array from ./NPT_F-trajectory/cp2k-1.cell 
array = np.loadtxt('./NPT_F-trajectory/cp2k-1.cell')
array = array[:, 2:11]
array = array.reshape(-1, 3, 3)
print(array.shape)

```

```stdout
(11, 3, 3)
```
```python
np.array_equal(dp['cells'], array)
```
```stdout
True
```

**Comment by robinzyb** [comment] 2023-12-26 10:50
still cp2kdata extract cell info from a `.cell` file if the `.cell` file is provided

**Comment by xiaohe-njust** [comment] 2023-12-26 11:26
> please provide the cp2k output files for me to debug.
> 
> ```
> Archive:  30GPa-last.frame.zip
>    creating: dpdata-30GPa-f20000/
>   inflating: dpdata-30GPa-f20000/box.raw  
>   inflating: dpdata-30GPa-f20000/coord.raw  
>   inflating: dpdata-30GPa-f20000/energy.raw  
>   inflating: dpdata-30GPa-f20000/force.raw  
>   inflating: dpdata-30GPa-f20000/type.raw  
>   inflating: dpdata-30GPa-f20000/type_map.raw  
>   inflating: cp2k-1.restart          
> ```
> 
> also, have you tried cp2kdata plugin? https://github.com/robinzyb/cp2kdata/tree/main

I just updated the version of cp2kdata.
It's able to extract box information from .cell files now, and it works for cp2k version 7.1 as well.

Thanks for your efforts!

**Comment by robinzyb** [comment] 2023-12-26 12:02
Indeed, I found it is a severe bug when transforming the angles and lengths to cell matrices. As shown by your figures, the code assumes the cell a axis are always aligned to x axis, the x coordinate, which is not ture. I have to add warning when parsing cell info from `cp2k.log/output` file

**Comment by robinzyb** [comment] 2023-12-26 12:05
by the way, how do you print `-1.cell` file in `input.inp`. I rarely use npt ensemble.

**Comment by xiaohe-njust** [comment] 2023-12-26 12:22
> by the way, how do you print `-1.cell` file in `input.inp`. I rarely use npt ensemble.

The instructions are similar to those for outputting force information, and are as follows

![image](https://github.com/deepmodeling/dpdata/assets/133549998/062f2eae-6653-474d-a11f-a83ad9623379)

**Comment by robinzyb** [comment] 2023-12-26 12:38
Thank you. If the problem has been solved, please close the issue as well.

**Comment by xiaohe-njust** [comment] 2023-12-26 12:45
> Thank you. If the problem has been solved, please close the issue as well.

Okay, thanks for your help.

**Closed** 2023-12-26 12:46 UTC
Labels: bug, cp2k
